import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/navbar';
import ClientOnly from './components/clientOnly';
import RegisterModal from './components/modals/registerModal';
import ToasterProvider from './providers/toasterProvider';

const typography = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Vocation Homes & Condo Rentals - Airbnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={typography.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
